spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipeapp_dev
    username: dev_user
    password: password_dev
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true